Fixes
duckdb/duckdb-wasm pull request #1194
Opened 2023-03-17 12:11 UTC by carlopi

Commits are unconnected.

* shell.ts -> I saw in some local configurations numbers out of 0-10
* npm's README was off, pointing to a specific version instead of latest
* GitHub and AWS returns 200 when range requests are valid, adapting to avoid full requests (note that accept-bytes is not accessible in most servers, so can't be checked

2023-03-17 12:22 UTC, ankoh requested changes

2023-03-17 12:22 UTC, ankoh commented on packages/duckdb-wasm-shell/src/shell.ts
> +            var blocks = Math.floor((progress.bytesLoaded / progress.bytesTotal) * 10.0);
Please use let instead of var

2023-03-17 12:22 UTC, ankoh commented on packages/duckdb-wasm-shell/src/shell.ts
> +            if (blocks < 0.0)
Brackets or max(blocks, 0.0) please

2023-03-20 12:08 UTC, carlopi commented
Updated the PR with the comments + adding a fall back for detecting whether range requests are accepted: asking explicitly for range 0-0 (instead of 0-) will give back 206 from raw.githubusercontent.com (and potentially other servers) at the cost of not providing *** full request length.

Proper solution for this would be a rework of checkFile, so that checkFile will also save/cache the length of the resource, but this is for a later refactor.

*** = Full request length is there, but filtered out by the browser

2023-03-20 16:14 UTC, ankoh approved these changes

2023-03-20 16:14 UTC, merged