Save queries in url hash segment, and restore them at startup
duckdb/duckdb-wasm pull request #1529
Opened 2023-12-14 11:18 UTC by carlopi

Idea is as follow:

Whenever a query is complete, it's stringified and it's representation it's appended to the hash segment of the URL.

If you are accessing a link like shell.duckdb.org/#queries=v0,string1,string2,string3 then the three queries encoded by those three string will be first executed, and then CLI returns control to user.

Demo is here:
https://carlopi.github.io/public-test-duckdb-wasm-spatial/#queries=v0,TE9BRCB0cGNoOw==,U0VMRUNUICdXYWl0IGZvciBhYm91dCAxMCBzZWNvbmRzLi4uJyBhcyBzdWdnZXN0aW9uOw==,Q0FMTCBkYmdlbihzZj0xKTs=,REVTQ1JJQkU7

Idea is allow ease of share URLs that directly encode significant examples. Both for us and for users.

Potential improvements:
- [ ] highlighter support
- [ ] better encoding than BTOA <-> ATOB

Does this makes sense to be exposed?

2023-12-15 09:13 UTC, carlopi commented
Update, logic is now as follow:

https://shell.duckdb.org/#queries=v0,SELECT-32~,PRAGMA-version~

Will on start up first execute all queries, here on the example `SELECT 32;` and then `PRAGMA version;`. Afterwards, business as usual. URL will remain unchanged, so sharing it will keep share the same initial hardcoded example.

https://shell.duckdb.org//#savequeries&queries=v0,SELECT-32~

If there is the extra `savequeries` segmentWill on start up first execute any queries (if any), then on every executed query, (after executiong) it will be appended to the queries segment of the URL.
This can be used to generate demo and example to be shared.

On sharing, if you remove the `savequeries` part, example will be locked in, otherwise the live update behaviour will be ON also for whoever open the links.

Going to https://shell.duckdb.org will be just the regular experience, given there are not queries to be executed nor saving is not enabled.

2023-12-15 10:37 UTC, Mause requested changes

2023-12-15 11:56 UTC, carlopi commented on packages/duckdb-wasm-shell/crate/src/shell.rs
> +		    Shell::with_mut(|s| {
Done! Thanks

2023-12-15 12:50 UTC, merged

2023-12-23 10:25 UTC, ericemc3 commented
This is a great addition, thanks!

And what about an export=csv parameter, allowing to get directly via URL a csv stream from the request passed? It could allow for automatic charting in DataWrapper for instance.